[server]
address = ":8080"
trusted-platform = ""
site_url = "http://localhost:8080"
api_key = "test-api-key-12345"

[shortener]
code_length = 6
code_charset = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

[admin]
username = "admin"
password = "admin123"

[database]
type = "sqlite"
log_level = 1

[database.sqlite]
path = ":memory:"

[cache]
enabled = false
type = "redis"
expire = 3600
prefix = "shorten:"

[geoip]
enabled = false
type = "ip2region"

[logging]
level = "debug"
format = "json"
with_timestamp = true
with_target = true
with_thread_ids = false
with_thread_names = false
with_file = false
with_line_number = false
with_ansi = true
